name: ending_file_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.1.2
  modal_bottom_sheet: ^2.1.2
  top_snackbar_flutter: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_screen_lock: ^9.0.1
  wechat_assets_picker: ^8.7.1
  video_player: ^2.8.1
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  url_launcher: ^6.2.1
  in_app_review: ^2.0.8
  purchases_flutter: ^6.4.0

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: ZenOldMincho-Bold
      fonts:
        - asset: assets/fonts/ZenOldMincho-Bold.ttf
    - family: ZenOldMincho-Regular
      fonts:
        - asset: assets/fonts/ZenOldMincho-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'
  adaptive_icon_background: '#000000'
  adaptive_icon_foreground: 'assets/images/icon_adaptive_foreground.png'
